# Generated by Django 5.0.6 on 2025-03-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
