# Generated by Django 5.0.6 on 2025-03-02 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_pdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="contract_text",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="signed_document_url",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="user",
        ),
        migrations.AddField(
            model_name="contract",
            name="document_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="recipient_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="user_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
