# Generated by Django 5.0.6 on 2025-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_contract_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="created_at",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
