# Generated by Django 5.0.6 on 2025-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contract_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
