# Generated by Django 5.2 on 2025-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_remove_contract_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusignprofile",
            name="base_uri",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
